logging:
  level:
    root: DEBUG
spring:
  profiles:
    active: test
  config:
    import: classpath:credentials.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 906995767347-fruvk9jt376vlubmihesvkn80s8421po.apps.googleusercontent.com
            client-secret: 
            scope:
              - openid
              - profile
              - email
server:
  address:
  port:
  forward-headers-strategy: framework
app:
  jwt:
    secret-key:
    secret-key-spare:
    secret-key-version:
    expiration-ms: 1500000 # 25 min.
    cookie-max-age-day: 45 # 45 days.
