spring:
  profiles:
    active: test
  config:
    import: classpath:credentials.yml
server:
  address:
  port:
  forward-headers-strategy: framework
app:
  jwt:
    secret-key:
    secret-key-spare:
    secret-key-version:
    expiration-ms: 1500000 # 25 min.
