spring:
# profiles:
#   active: "dev"
  config:
    import: classpath:credentials.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "906995767347-fruvk9jt376vlubmihesvkn80s8421po.apps.googleusercontent.com"
            client-secret:
            scope:
              - openid
              - profile
              - email
  datasource:
    url: jdbc:mariadb://i8:3306/ao_login
    username: ao_login
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  session:
    jdbc:
      data-source-name: session-data-source
session-data-source:
  jdbcUrl: jdbc:mariadb://i8:3306/ao_session
  username: ao_login
  password:
  driver-class-name: org.mariadb.jdbc.Driver
jwt:
  secret-key:
  expiration-ms: 1500000 # 25 min.
server:
  address:
  port:
  forward-headers-strategy: framework
